### ISSUE TITLE
It does not seem to work on ALL modules.

### ISSUE THREAD

**Issue by joseph-jja** [domenic/amd-wrap#7]
So I did npm install jqueryui and then ran it through amd-wrap. I then dump it into a directory called jqueryui-amd.   It looks like amd-wrap wraps all the files, but for some reason doing a require on jqueryui-amd/dialog fails, but doing a require on jqueryui-amd/spinner works.  Is this a require issue or an issue in wrapping?

var data;
// loop through each file, I am using grunt recurse so absFname is the filename 
data = grunt.file.read( absFname );
// make the file have jqueryui-amd/ module name
data = data.replace( jqamdPath, '$1jqueryui-amd/' );
data = amdWrap( data );
grunt.file.write(  "jqueryui-amd" + sep + file, data );               

The files all get wrapper but not all work?

**Comment by domenic** [comment]
jQuery UI presumably doesn't use `module.exports`. This tool isn't meant to magically convert scripts into AMD modules. Instead it's used for taking files that are already in CommonJS format and wrapping them. From the readme:

> All this module does is wrap your CommonJS modules into the simplified CommonJS wrapper format

**Comment by joseph-jja** [comment]
So the files are wrapped, and some work, but others don't.  More of an issue of how the jquery ui is done as common js modules.

**Comment by domenic** [comment]
Hmm yeah, I guess so. I was under the impression jQuery UI didn't use CommonJS at all, but maybe they do these days...
